### ISSUE TITLE
Clustering layer points: Layer is not displayed in the layer list

### ISSUE THREAD

**Issue by michellemoine** [tomchadwin/qgis2web#197]
http://bassinefe-liege.be/qgis2web_cluster

**Comment by tomchadwin** [comment]
Confirmed. Looking into it now.

**Comment by tomchadwin** [comment]
Obviously, if I can work out how to fix this, the icon will reflect the unclustered style.

**Comment by tomchadwin** [comment]
Fixed in master - please test.

**Comment by michellemoine** [comment]
Thanks Tom. It's working now.

**Comment by tomchadwin** [comment]
Thanks so much for this and all the other incredibly precise and useful bug reports and fix tests @michellemoine. Very, very much appreciated. It's made a real difference to the plugin, and couldn't have happened at a better time, immediately before 1.0.0.

**Comment by michellemoine** [comment]
Thanks to you helping me shaping up my project. I still have another issue that I'll open another one for it.

**Comment by tomchadwin** [comment]
Keep 'em coming...

**Comment by tomchadwin** [comment]
Released as 1.0.0-RC3 and pushed to QGIS plugins repo
