### ISSUE TITLE
Hidden fields not available as labels or categorization/graduation fields

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#326]
This is a serious bug, uncovered by @magerlin, which will require some thought to solve. I don't know how to yet.

**Comment by tomchadwin** [comment]
Possible vague solutions:

1. Identify hidden fields required for labels or styles (I don't know how), and incorporate them with a namespacing prefix of `qgis2web_` or `q2wHide_`, then only add fields to the popup which don't have that prefix

2. Use the approach implemented for the OL3 images and aliases suggested by @ThomasG77 which could be cleaner, but I don't know if it will port to Leaflet (can I add user-defined layer vars in Leaflet?)

1 might be quite easily doable, so I might investigate that first, at least for Leaflet. I take it this issue is present for OL3 as well?

**Comment by tomchadwin** [comment]
Leaflet behavious possibly fixed in master - please test:

- labelling with hidden field
- categorizing on hidden field
- graduating on hidden field

OL3 still to do - that's for next week.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by tomchadwin** [comment]
Released as 1.14.0 and pushed to QGIS plugins repo.

**Comment by magerlin** [comment]
Test: It works ok

**Comment by tomchadwin** [comment]
Great - thanks for testing.

**Comment by joooeey** [comment]
What's a hidden field? How do I hide a field? I tried hiding the field in the Attribute Table but that has no effect on qgis2web, i.e. the field is still shown in the popup.

I would find it way more intuitive to add the option to hide a field to the label dropdown in the Layers and Groups tab of the qgis2web dialog.
