### ISSUE TITLE
AttributeError : 'NoneType' object has no attribute 'symbolLayer'

### ISSUE THREAD

**Issue by achos01** [tomchadwin/qgis2web#629]
- QGIS version 2.18.17
- qgis2web version 2.33.1 
- Using the option 'Style through rules' in Styles window.

**When i try to export a layer into html page with qgis2web i have this error :** 

qgis2web produced an error:

Traceback (most recent call last):
File "C:/Users/ACH/.qgis2/python/plugins\qgis2web\maindialog.py", line 318, in previewMap
preview_file = self.createPreview()
File "C:/Users/ACH/.qgis2/python/plugins\qgis2web\maindialog.py", line 280, in createPreview
dest_folder=utils.tempFolder()).index_file
File "C:/Users/ACH/.qgis2/python/plugins\qgis2web\olwriter.py", line 89, in write
folder=dest_folder)
File "C:/Users/ACH/.qgis2/python/plugins\qgis2web\olwriter.py", line 128, in writeOL
popup, json, restrictToExtent, extent, feedback, matchCRS)
File "C:/Users/ACH/.qgis2/python/plugins\qgis2web\utils.py", line 180, in exportLayers
iface, extent, precision, crs, optimize)
File "C:/Users/ACH/.qgis2/python/plugins\qgis2web\utils.py", line 194, in exportVector
if is25d(layer, canvas, restrictToExtent, extent):
File "C:/Users/ACH/.qgis2/python/plugins\qgis2web\utils.py", line 448, in is25d
sl1 = sym.symbolLayer(1)
AttributeError: 'NoneType' object has no attribute 'symbolLayer'

_Thanks in advance._

**Comment by tomchadwin** [comment]
Please see my response to another issue here:

https://github.com/tomchadwin/qgis2web/issues/628#issuecomment-375692556

This is not the same problem, but that answer should help you provide what is needed for someone to be able to debug this issue properly.

**Comment by tomchadwin** [comment]
I've committed a possible fix to master for #628 which *might* also fix this issue. Can you test and report back?

**Comment by achos01** [comment]
I do not know how to solve this problem, can not find the solution anywhere

**Comment by tomchadwin** [comment]
Please try upgrading to qgis2web 3.0.1, now available in the QGIS plugin manager. Please report back on whether the error still occurs with 3.0.1

**Comment by tomchadwin** [comment]
Closed without further feedback - comment here and I'll reopen.

**Comment by galihalhakim** [comment]
i'm using QGIS 3 and still have this error.

AttributeError: 'NoneType' object has no attribute 'symbolLayer' 
Traceback (most recent call last):
  File "C:/Users/GALIH/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 323, in previewMap
    preview_file = self.createPreview()
  File "C:/Users/GALIH/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 286, in createPreview
    dest_folder=utils.tempFolder()).index_file
  File "C:/Users/GALIH/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 100, in write
    folder=dest_folder)
  File "C:/Users/GALIH/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 187, in writeLeaflet
    exp_crs, minify)
  File "C:/Users/GALIH/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 234, in exportVector
    if is25d(layer, canvas, restrictToExtent, extent):
  File "C:/Users/GALIH/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 490, in is25d
    sl1 = sym.symbolLayer(1)
AttributeError: 'NoneType' object has no attribute 'symbolLayer'

**Comment by M-Rick** [comment]
I am running QGIS 3.10.11 and still have the error as well.
![Capture d’écran 2020-10-30 à 20 32 00](https://user-images.githubusercontent.com/2520948/97749267-0e0a6400-1aef-11eb-906d-b0ea8b147fbf.png)
