### ISSUE TITLE
WFS Layers Not Exporting

### ISSUE THREAD

**Issue by aloerch** [tomchadwin/qgis2web#773]
I am using QGIS 3.8 with the latest qgis2web version (2019/05/09 3.7.0).

I have 2 layers added in QGIS, a WMS basemap that exports fine, and a WFS point layer (25 points) that does not export properly unless I check the "encode to JSON" option (more on that in a moment). 

The SRS of both layers on my Geoserver and my QGIS project SRS is EPSG:2230.

When I export the project using qgis2web, the WFS layer does not display on the map. Using Chrome's inspector on the HTML page, I can see the error: net::ERR_FILE_NOT_FOUND associated with the link: 
`file:///C:/Users/#myusername#/AppData/Local/Temp/qgis2web/qgis2web_2019_07_13-01_18_19_280121/pageSize='1000000'%20pagingEnabled='true'%20srsname='EPSG:2230'%20typename='terraBella:Ground_Control'%20url='http://#a-web-address#.com:8080/geoserver/terraBella/wfs'%20version='2.0.0'%20table=`

Looking at the HTML code, there is this (near the end of the index.html file):
        `<script src=" pageSize='1000000' pagingEnabled='true' srsname='EPSG:2230' typename='terraBella:Ground_Control' url='http://#a-web-address#.com:8080/geoserver/terraBella/wfs' version='2.0.0' table="" sql=&outputFormat=text%2Fjavascript&format_options=callback%3AgetGroundControlPoints_1Json"></script>`

^^ that doesn't seam right...

Looking in the layers folder, there is just layers.js, and that has:

```
var jsonSource_GroundControlPoints_1 = new ol.source.Vector({
    attributions: '<a href=""></a>',
    format: format_GroundControlPoints_1
});var lyr_GroundControlPoints_1 = new ol.layer.Vector({
    declutter: true,
    source: jsonSource_GroundControlPoints_1, 
    style: style_GroundControlPoints_1,
    title: "Ground Control Points"
});

function getGroundControlPoints_1Json(geojson) {
    var features_GroundControlPoints_1 = format_GroundControlPoints_1.readFeatures(geojson);
    jsonSource_GroundControlPoints_1.addFeatures(features_GroundControlPoints_1);
}

lyr_Flight1BaselineOrthomosaic_0.setVisible(true);lyr_GroundControlPoints_1.setVisible(true);
var layersList = [lyr_Flight1BaselineOrthomosaic_0,lyr_GroundControlPoints_1];
lyr_GroundControlPoints_1.set('fieldAliases', {'Name': 'Name', 'Elevation': 'Elevation', 'xcoord': 'xcoord', 'ycoord': 'ycoord', });
lyr_GroundControlPoints_1.set('fieldImages', {'Name': 'TextEdit', 'Elevation': 'TextEdit', 'xcoord': 'TextEdit', 'ycoord': 'TextEdit', });
lyr_GroundControlPoints_1.set('fieldLabels', {'Name': 'no label', 'Elevation': 'no label', 'xcoord': 'no label', 'ycoord': 'no label', });
lyr_GroundControlPoints_1.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});

```
^^ which also doesn't look right...

So, if I use 'encode to JSON', both layers end up working fine. I get a 2nd file in the layers folder for the ground_control layer, and all is good... except what I REALLY am trying to accomplish is having 5 WMS basemaps in a layer group, and 6 WFS point/polyline layers in another layer group. However, when I create the layer groups, the 'encode to JSON' option is no longer available for the WFS layers, meaning I cannot use that option. Also, It could be useful for me to update the features in the WFS layers from time to time, meaning having them exported as JSON files is not the most ideal solution, even if it were possible. 

Please let me know if I can help out at all. I'm not a complete noob; I do quite a bit of python development, and I used to create openlayers webmaps from scratch, but gave up after the changes in openlayers 3 version 5+.

**Comment by aloerch** [comment]
I've read through every closed issue I could find regarding WFS. I'm not working with filters, the styling is the default random point coloring from qgis.

Here is the correct WFS request/url for my server:

[](http://ec2-18-209-166-192.compute-1.amazonaws.com:8080/geoserver/terraBella/wfs?SERVICE=WFS&VERSION=1.1.0&REQUEST=GetFeature&TYPENAME=terraBella%3AGround_Control&SRSNAME=EPSG:2230)

**Comment by tomchadwin** [comment]
That definitely doesn't look right. Worryingly, though, my first attempt at testing this (with a different WFS) has led to a Python error. So, I'll look into it and see if I can figure out the issue(s).

**Comment by tomchadwin** [comment]
OK, I've fixed the Python error (a function call hadn't been updated with the new optional popups feature), and my test WFS works. I'll now have a look at yours.

**Comment by tomchadwin** [comment]
Scratch that - tentatively, it appears to be exporting WFSes to JSON regardless of the setting chosen in the GUI. Investigating.

**Comment by aloerch** [comment]
Thank you for working on this! Yes, i was confused about why the javascript seems to be describing a json layer even when the wfs option was explicitly selected. Aside from this issue, im duly impressed by qgis2web, and look forward to having such a simple method for creating web mapping clients.

**Comment by tomchadwin** [comment]
I was wrong - when selected, the WFS layers are exporting as WFS. The issue seems likely to e that the Geoserver instance has not had JSONP enabled. It is disabled by default, but that is what qgis2web uses. See the Geoserver docs for more information, and let us know if this is indeed the issue (and whether you are able to fix it): https://docs.geoserver.org/latest/en/user/services/wfs/outputformats.html

**Comment by aloerch** [comment]
I set the jsonp enable parameter to true, and restarted my geoserver. 

qgis2web still does not export a working wfs layer. The layers.js file looks better, but it is still the only file in the layers folder and index.html still fails in chrome with the original error about the file associated with the wfs layer not being found. 

Are you able to display my linked wfs layer in an exported qgis2web map?
