### ISSUE TITLE
Heatmap not showing for ESPG:4326 CRS (OLS and Leaflet)

### ISSUE THREAD

**Issue by kgorro** [tomchadwin/qgis2web#880]
Heatmap is not showing when exporting to web map using qgis2web.
QGIS version: 3.10.2
CRS: ESPG:4326
XYZ Tiles: OpenStreetmap

**Comment by tomchadwin** [comment]
Can you upload your files? Any JS errors in the browser console?

**Comment by kgorro** [comment]
I will post, I am still rendering the map with the heatmap only and I will post it after this one.

**Comment by kgorro** [comment]
Below are the errors in the console:
leaflet.js:5 Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error
    at file:///C:/Users/HP/AppData/Local/Temp/qgis2web/qgis2web_2020_05_11-23_31_05_292252/js/leaflet.js:5:3222
    at Function.S.extend (file:///C:/Users/HP/AppData/Local/Temp/qgis2web/qgis2web_2020_05_11-23_31_05_292252/js/leaflet.js:5:3240)
    at file:///C:/Users/HP/AppData/Local/Temp/qgis2web/qgis2web_2020_05_11-23_31_05_292252/js/leaflet.pattern.js:6:34
    at file:///C:/Users/HP/AppData/Local/Temp/qgis2web/qgis2web_2020_05_11-23_31_05_292252/js/leaflet.pattern.js:6:7077
(anonymous) @ leaflet.js:5
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/HP/AppData/Local/Temp/qgis2web/qgis2web_2020_05_11-23_31_05_292252/js/Autolinker.min.js.map: System error: net::ERR_FILE_NOT_FOUND

Then at some point, before the page is completely loaded, I got this:
![image](https://user-images.githubusercontent.com/49682861/81580427-01c70900-93e0-11ea-9424-ed4d21d09959.png)

**Comment by tomchadwin** [comment]
Neither of those errors relate to this issue. Can you upload your QGIS project and layer files?

**Comment by kgorro** [comment]
Please check this, thanks.
[qgis_issue.zip](https://github.com/tomchadwin/qgis2web/files/4620402/qgis_issue.zip)

**Comment by tomchadwin** [comment]
OK, that project is in ESG:3857. I changed it to EPSG:4326 and checked "Match project CRS". It works in Leaflet. However, In OpenLayers, I get the following error:

```
ndexError: list index out of range 
Traceback (most recent call last):
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 190, in changeFormat
    self.autoUpdatePreview()
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 334, in autoUpdatePreview
    self.previewMap()
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 337, in previewMap
    preview_file = self.createPreview()
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 300, in createPreview
    dest_folder=utils.tempFolder()).index_file
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 91, in write
    folder=dest_folder)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 160, in writeOL
    minZoom, matchCRS, mapSettings)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 384, in getCRSView
    fullextent, units[unit])
IndexError: list index out of range
```

I'll investigate.

**Comment by kgorro** [comment]
I change now to EPSG:4326 and Match project CRS but I got this output:
![image](https://user-images.githubusercontent.com/49682861/81791418-4adea080-9539-11ea-9267-7462a8839ea6.png)

Is this what you are seeing?

**Comment by tomchadwin** [comment]
Possible fix committed to master. Please test and report back.

**Comment by tomchadwin** [comment]
@kgorro Yes, that is what I am seeing. Is it not correct?

**Comment by kgorro** [comment]
@tomchadwin , I think not since in the original heatmap it is not having that output and the openstreetmap is not showing.

**Comment by tomchadwin** [comment]
Openstreetmap won't be displaying because the tile provider has only supplied tiles in EPSG:3857. If the display of the heatmap is not identical to QGIS, I'll need some help in improving heatmap output.

**Comment by tomchadwin** [comment]
The OpenLayers projection fix has been released in 3.14.0.

**Comment by boredtea** [comment]
> Possible fix committed to master. Please test and report back.

Hello, I've been having the same issue and I have the updated version of the plugin. The heatmap only shows up in the OpenLayers preview and doesn't show up at all in Leaflet or Mapbox. Moreover, the OpenLayers heatmap is not identical to the QGIS heatmap: the heatmap in OpenLayers is all huge and blotchy.

When I match project CRS, the heatmap appears in all three (but is still not the same as the QGIS one) and the OSM disappears.
